# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='img',
            field=models.ImageField(blank=True, upload_to='./ media'),
        ),
    ]
