# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0003_paper_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('interest', models.CharField(max_length=300)),
                ('image', models.URLField(null=True)),
                ('rsdirection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Rsdirection')),
            ],
        ),
    ]
