# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='body',
        ),
        migrations.RemoveField(
            model_name='research',
            name='title',
        ),
        migrations.AddField(
            model_name='research',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='research',
            name='orientation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='research',
            name='projectorigin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='research',
            name='rank',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='research',
            name='time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
