# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20180428_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
