# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=300)),
                ('awardname', models.CharField(blank=True, max_length=300)),
                ('projectname', models.CharField(blank=True, max_length=300)),
                ('company', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
